AWSTemplateFormatVersion: '2010-09-09'
Description: Test database
Parameters:
  TestTableReadCapacity:
    Type: Number
  TestTableWriteCapacity:
    Type: Number
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Test table
        Parameters:
          - TestTableReadCapacity
          - TestTableWriteCapacity
Resources:
  TestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: test-table
      AttributeDefinitions:
        - {AttributeName: id, AttributeType: S}
        - {AttributeName: name, AttributeType: S}
      KeySchema:
        - {AttributeName: id, KeyType: HASH}
        - {AttributeName: name, KeyType: RANGE}
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref TestTableReadCapacity
        WriteCapacityUnits: !Ref TestTableWriteCapacity